# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WO_0Fej3kqG3MwvbB6rVyZvKdDaz3BMD
"""

x1=float(input("Enter x1:"))
y1=float(input("Enter y1:"))
z1=float(input("Enter z1:"))

x2=float(input("Enter x2:"))
y2=float(input("Enter y2:"))
z2=float(input("Enter z2:"))

d = x1 * y2 - x2 * y2

if d == 0:
    print("No unique solution.")
else:
    x = (z1 * y2 - z2 * y1) / d
    y = (x1 * z2 - x2 * z1) / d

    print("x =", x)
    print("y =", y)